sudo: required
services:
  - docker

before_install:
  - docker build -t nejiang/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nejiang/react-test npm test -- --coverage

after_success:
  - docker build -t nejiang/multi-client ./client
  - docker build -t nejiang/multi-nginx ./nginx
  - docker build -t nejiang/multi-server ./server
  - docker build -t nejiang/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push nejiang/multi-client
  - docker push nejiang/multi-nginx
  - docker push nejiang/multi-server
  - docker push nejiang/multi-worker

# deploy:
#   provider: elasticbeanstalk
#   region: us-east-2
#   app: multi-docker
#   env: MultiDocker-env
#   bucket_name: elasticbeanstalk-us-east-2-517901360390
#   bucket_path: docker-multi
#   on: 
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: 
#     secure: $AWS_SECRET_KEY
    



